stderr of test 'truncate_geom_tables.Bug-6543` in directory 'sql/test/BugTracker-2018` itself:


# 15:22:47 >  
# 15:22:47 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=35943" "--set" "mapi_usock=/var/tmp/mtest-12540/.s.monetdb.35943" "--set" "monet_prompt=" "--forcemito" "--dbpath=/ufs/sjoerd/@Monet-candidate/var/MonetDB/mTests_sql_test_BugTracker-2018" "--set" "embedded_c=true"
# 15:22:47 >  

# builtin opt 	gdk_dbpath = /ufs/sjoerd/@Monet-candidate/var/monetdb5/dbfarm/demo
# builtin opt 	monet_prompt = >
# builtin opt 	monet_daemon = no
# builtin opt 	mapi_port = 50000
# builtin opt 	mapi_open = false
# builtin opt 	mapi_autosense = false
# builtin opt 	sql_optimizer = default_pipe
# builtin opt 	sql_debug = 0
# cmdline opt 	gdk_nr_threads = 0
# cmdline opt 	mapi_open = true
# cmdline opt 	mapi_port = 35943
# cmdline opt 	mapi_usock = /var/tmp/mtest-12540/.s.monetdb.35943
# cmdline opt 	monet_prompt = 
# cmdline opt 	gdk_dbpath = /ufs/sjoerd/@Monet-candidate/var/MonetDB/mTests_sql_test_BugTracker-2018
# cmdline opt 	embedded_c = true
#client2:!ERROR:ParseException:SQLparser:42000!TRUNCATE: insufficient privileges for user 'testuser' to truncate table 'spatial_ref_sys'
#main thread:!ERROR:MALException:client.quit:Server stopped

# 15:22:47 >  
# 15:22:47 >  "mclient" "-lsql" "-ftest" "-tnone" "-Eutf-8" "-i" "-e" "--host=/var/tmp/mtest-12540" "--port=35943" "-utestuser" "-Ptestpassword"
# 15:22:47 >  

MAPI  = (testuser) /var/tmp/mtest-12540/.s.monetdb.35943
QUERY = TRUNCATE TABLE sys.spatial_ref_sys;
ERROR = !TRUNCATE: insufficient privileges for user 'testuser' to truncate table 'spatial_ref_sys'
CODE  = 42000

# 15:22:47 >  
# 15:22:47 >  "Done."
# 15:22:47 >  

