stderr of test 'error-clean-cache.Bug-6351` in directory 'sql/test/BugTracker-2017` itself:


# 15:10:19 >  
# 15:10:19 >  "mserver5" "--debug=10" "--set" "gdk_nr_threads=0" "--set" "mapi_open=true" "--set" "mapi_port=36136" "--set" "mapi_usock=/var/tmp/mtest-222580/.s.monetdb.36136" "--forcemito" "--dbpath=/home/ferreira/repositories/MonetDB-Nov2019/BUILD/var/MonetDB/mTests_sql_test_BugTracker-2017" "--set" "embedded_r=yes" "--set" "embedded_py=2" "--set" "embedded_c=true"
# 15:10:19 >  

MAPI  = (monetdb) /var/tmp/mtest-188873/.s.monetdb.33831
QUERY = declare a int;
ERROR = !Variables cannot be declared on the global scope
CODE  = 42000
MAPI  = (monetdb) /var/tmp/mtest-188873/.s.monetdb.33831
QUERY = select a;
ERROR = !SELECT: identifier 'a' unknown
CODE  = 42000
MAPI  = (monetdb) /var/tmp/mtest-188873/.s.monetdb.33831
QUERY = iamerror; --just an error
ERROR = !syntax error, unexpected IDENT in: "iamerror"
CODE  = 42000
MAPI  = (monetdb) /var/tmp/mtest-188873/.s.monetdb.33831
QUERY = select a; --a is not there
ERROR = !SELECT: identifier 'a' unknown
CODE  = 42000

# 15:10:20 >  
# 15:10:20 >  "Done."
# 15:10:20 >  

